### ISSUE TITLE
iOS SDWebImage can not load PNG image

### ISSUE THREAD

**Issue by qq6931850** [rs/SDWebImage#1335]
TEST URL:http://api.buzz.cn/Public/Upload/pptpdf/2014/12/31/1420003484645/1420003509_1.png
I know the error is about: Downloaded image has 0 pixels，But sdwebimage before ios9 can also be accessed.How can I adjust so that I can access load the image

**Comment by qq6931850** [comment]
I have a lot of link like this.

**Comment by mythodeia** [comment]
If it's only IOS9 check [this](http://www.fiveminutewatchkit.com/blog/?category=NSURLSession)

**Comment by mythodeia** [comment]
I still cannot access the link you posted. Are you sure it's working? Open the sample project and remove the default urls and add your own and test

**Comment by mythodeia** [comment]
i debugged the issue and it seems to be triggering the following warning when ```CGBitmapContextCreate``` is running in ```SDWebImageDecoder.m``` file
```
CGBitmapContextCreate: unsupported parameter combination: 16 integer bits/component; 64 bits/pixel; 3-component color space; kCGImageAlphaPremultipliedFirst; 8000 bytes/row.
```

**Comment by qq6931850** [comment]
is this the image you are trying to access? 
-------
yes，it is

 debugged the issue and it seems to be triggering the following warning when CGBitmapContextCreate is running in SDWebImageDecoder.m file

-----
i debugged the url have the same warning

**Comment by qq6931850** [comment]
Before I use ios8 xcode6 is not the problem, and the picture can also be a correct view

**Comment by qq6931850** [comment]
i have another warning , i think this may have a relationship

<Error>: CGBitmapContextCreate: unsupported parameter combination: set CGBITMAP_CONTEXT_LOG_ERRORS environmental variable to see the details

 <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

<Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

**Comment by mythodeia** [comment]
add this:
```
    if (!context) {
        if (unsupportedColorSpace){
            CGColorSpaceRelease(colorspaceRef);
        }
        return image;
    }
```
after this:
```
 CGContextRef context = CGBitmapContextCreate(NULL, width,
                                                 height,
                                                 CGImageGetBitsPerComponent(imageRef),
                                                 0,
                                                 colorspaceRef,
                                                 kCGBitmapByteOrderDefault | kCGImageAlphaPremultipliedFirst);
```

**Comment by qq6931850** [comment]
thank you . The problem is solved.

**Comment by CokeBear** [comment]
@mythodeia   thank you very much .  I use  the version  3.7.4  and   try your code .  The problem is solved.

**Comment by haifuyun** [comment]
@mythodeia  Thank you for your answer to help me solve this problem！

**Comment by mythodeia** [comment]
:+1:

**Comment by dengzhp** [comment]
+1, same problem here. why not commit this patch to repo?

**Comment by mythodeia** [comment]
@dengzhp can you try with the latest commits? this should be resolved

**Comment by dengzhp** [comment]
@mythodeia yes, specifying ':head' in Podfile fix this problem, while the latest release '3.7.5' still has this problem. Thanks.

**Comment by solidfox** [comment]
For those using CocoaPods 1.0 :head was removed. Use :git instead:    
`pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git'`

**Comment by StYaphet** [comment]
Thank you. @mythodeia the same problem and solved

**Comment by mamaral** [comment]
I'm having this same issue with images I have no problem viewing in the browser. I am also using `pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git'` as @solidfox suggested, which upped my version from 3.7.5 to 3.8.1, but I still can't download any images. Any ideas on this one - this is unfortunately effecting one of my production clients. Note, I am using SDWebImageManager:

```
[[SDWebImageManager sharedManager] downloadImageWithURL:imageURL options:SDWebImageHighPriority progress:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
    handler(image);
}];
```

**Comment by mamaral** [comment]
Interesting part is that loading the images normally in things like table view cells works fine using the normal sd_setImage methods, but trying to use the `SDWebImageManager` results in these failures.

**Comment by mamaral** [comment]
Apparently the issue was the image was WebP (I had no idea) and I didn't have that part of the library installed.

**Comment by bpoplauschi** [comment]
@mamaral glad you found the issue :)

**Comment by SrdjanSpasojevic** [comment]
@mythodeia Thank you so much! :)
